models:
  voltage_battery: "models/Voltage-Battery.pth"
  current_battery: "models/Current-Battery.pth"
  voltage_solar: "models/Voltage-Solar.pth"
  current_solar: "models/Current-Solar.pth"

thresholds:
  voltage_battery: 19
  current_battery: 13
  voltage_solar: 85
  current_solar: 25
