data:
    input: "input"
    output: "output"
models:
  Voltage-Battery: "models/Voltage-Battery.pth"
  Current-Battery: "models/Current-Battery.pth"
  Voltage-Solar: "models/Voltage-Solar.pth"
  Current-Solar: "models/Current-Solar.pth"
  Voltage-battery-predictor: "models/predictorVb2424_cpu.ckpt"

thresholds:
  Voltage-Battery: 19
  Current-Battery: 13
  Voltage-Solar: 85
  Current-Solar: 25
